### ISSUE TITLE
Build failures from USM header

### ISSUE THREAD

**Issue by EwanC** [intel/compute-samples#9]
Hello, I was building this project to try the USM tests and countered the following couple of issues with the USM header file `cl_intel_unified_shared_memory.h` to successfully compile.

* Needed to add `extern "C"` linkage around new [entry points](https://github.com/intel/compute-samples/blob/38d4d9c9da1b15d51ebb7f73fcc99f4ddd07c7fa/compute_samples/core/ocl_entrypoints/include/ocl_entrypoints/cl_intel_unified_shared_memory.h#L77-L169)

* [clMemFreeINTEL](https://github.com/intel/compute-samples/blob/38d4d9c9da1b15d51ebb7f73fcc99f4ddd07c7fa/compute_samples/core/ocl_entrypoints/include/ocl_entrypoints/cl_intel_unified_shared_memory.h#L107) has `const void *ptr` as the second parameter when the spec defines `void*` ptr without the `const`.

**Comment by ltowarek** [comment]
Hi,

Thanks for reporting this issue! Based on the fact that USM headers are already in [cl_ext_intel.h](https://github.com/KhronosGroup/OpenCL-Headers/blob/master/CL/cl_ext_intel.h) we do not need to provide our own entry points. I will let you know when we will switch to cl_ext_intel.h.

Regarding compilation issues, that's strange because [Linux](https://travis-ci.org/github/intel/compute-samples/jobs/732991927), [Windows](https://ci.appveyor.com/project/intel/compute-samples/builds/35576028) and [Docker](https://hub.docker.com/repository/docker/intelotc/compute-samples/builds) builds work fine. Could you send us your configuration (OS/compiler/build steps) where compute-samples do not compile successfully?

Regards,
Lukasz

**Comment by EwanC** [comment]
Thanks for the reply Lukasz, using the public OpenCL-Headers repo definitely seems the best resolution to this.

I was building on Ubuntu 18.04 with gcc/g++ 7.5. However, the fail might be hard to repro as I was linking against an install of our own OpenCL with an under-development implementation of the USM extension. So was getting 'conflicting declaration' errors between `cl_intel_unified_shared_memory.h` and the header file from our own install.

**Comment by ltowarek** [comment]
We switched to cl_ext_intel.h in 6a573e440a1f98b8f3bd082433c300309d920d3a. @EwanC if you will see any other issue please let us know!
